# Configuring our pre-commit hooks to be used with pre-commit: https://pre-commit.com/

# Markdown specific hooks

# https://github.com/tcort/markdown-link-check
- id: markdown-link-check
  name: markdown-link-check
  description: Markdown-link-check checks all of the hyperlinks in a markdown text to determine if they are alive or dead.
  entry: pre_commit_hooks/markdown/markdown-link-check.sh
  language: script
  files: \.md$
  args: []
  exclude: >
    (?x)^(
      .+\.vendor\/.*$|
      .+\.terraform\/.*$|
    )$
  minimum_pre_commit_version: 0.15.0
