# ----------------------------------------------------------------------------------------------------------------------
# GOLANG LINTER RULES EXAMPLE
# ----------------------------------------------------------------------------------------------------------------------

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  skip-dirs:
    - .gen
    - node_modules
  skip-files:
    - ".*_gen\\.go$"
    - ".resolvers\\.go$"

output:
  format: colored-line-number

service:
  prepare:
    - GO111MODULE=on go mod vendor # required currently or golangci breaks

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gochecknoglobals
        - gochecknoinits
        - unused
        - paralleltest
        - staticcheck
        - ineffassign
        - unparam
    - path: cmd/
      linters:
        - gocyclo
        - dupl
        - gochecknoglobals
        - gochecknoinits
        - exhaustivestruct
linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dupl
    - errcheck
    - gocritic
    - gofmt
    - goconst
    - goimports
    - gosec
    - gosimple
    - golint
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
    ignore: fmt:.*,[rR]ead|[wW]rite|[cC]lose,io:Copy
  govet:
    # report about shadowed variables
    check-shadowing: true
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 15
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
