# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up
---
version: "3.6"

services:
  app:
    image: python:3.8.0
    environment: &environment
      - STAGE=dev
    volumes:
      - .:/usr/src
