name: lint-code

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

env:
  IMAGE_NAME: 'hadenlabs/pre-commit-hooks'

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
      - name: generate image docker
        if: ${{ !env.ACT }}
        run: |
          docker build --no-cache ./ --tag ${{ env.IMAGE_NAME }}:latest
      - name: validate files
        run: |
          docker run --rm -it --volume $PWD:/data ${{ env.IMAGE_NAME }}:latest pre-commit run --all-files
