name: lint-code

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

  push:
    branches:
      - main

    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      # https://semver.org/ proper release tags, more or less
      - "v[0-9]+.[0-9]+.[0-9]+"
      # prerelease tags, more or less
      - "v[0-9]+.[0-9]+.[0-9]+-*"

env:
  TASK_X_REMOTE_TASKFILES: 1
  IMAGE_NAME: 'hadenlabs/pre-commit-hooks'

permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
      - name: sync submodule
        run: |
          git submodule init
          git submodule update

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build the docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: validate files
        run: |
          docker run --rm --volume $PWD:/data ${{ env.IMAGE_NAME }}:latest pre-commit run --all-files
